### ISSUE TITLE
Validator Rewards

### ISSUE THREAD

**Issue by Donk3ys** [bnb-chain/node-deploy#54]
Are there any steps to get the validators to pay out rewards?

Ive followed [create validator](https://docs.bnbchain.org/docs/bcfusion/validators/creation/) section in the BSC docs but my validator hasn't received any rewards.

- Ive created a cluster of one node using the start_cluster.sh script.
- Then created a validator using the operator address (0xbCDD0d2cDA5f6423E57B6a4dCD75DEcbE31aeCf0) from the 1st node created.
- When creating the validator I sent a value of 2101 BNB to be delegated.

```
  const operatorAddress = '0xbCDD0d2cDA5f6423E57B6a4dCD75DEcbE31aeCf0'
  const consensusAddress = "0xbCDD0d2cDA5f6423E57B6a4dCD75DEcbE31aeCf0"
  const voteAddress = "0xb3baf71dc234890671fc3292afde45e20ce83cb8cd65c614be9fa29932c34051a75cbc1e25b968cc72142c91a56b521a"
  const blsProof = "0x98b4ca4128a64042b75d7233c687f872e5be35b6332841a073d2c5083adf3be68681bf31a20bce3c5bdf1ad5d131c5971927bee52d68e0471a2c627991256f06e89dae2c150b2d3fd0a27af4ed514cc55d87f4e7f15ee8dfb3b36cdda13572c1"
  const commission = {
    rate: 1000,
    maxRate: 2000,
    maxChangeRate: 100,
  } 
  const description = {
    moniker: "Val1",
    identity: "0xbCDD0d2cDA5f6423E57B6a4dCD75DEcbE31aeCf0",
    website: "google.com",
    details: "test details"
  }
```

The validator Credit Contract never gets rewards paid to it.
Ive let the validator run for 2days with no rewards paid

**Validator/Chain stats Stats**
Rewards contract 0x0000000000000000000000000000000000001002 **balance 51018134375000000**
Created Time: 1715754969
Jailed: false
Jail Until: 0
Operator: 0xbCDD0d2cDA5f6423E57B6a4dCD75DEcbE31aeCf0 **getValidatorRewardRecord 0**
Operator: 0xbCDD0d2cDA5f6423E57B6a4dCD75DEcbE31aeCf0 Credit Contract: 0x4AFc633E7B6bEB8e552ccddbE06Cca3754991E9A
Credit contract 0x4AFc633E7B6bEB8e552ccddbE06Cca3754991E9A **balanceOf 2100000000000000000000**

**Comment by buddh0** [comment]
the rewards comes from the fee of executing txs, so you can use txbot to send some transactions

**Comment by Donk3ys** [comment]
> the rewards comes from the fee of executing txs, so you can use txbot to send some transactions

Thank you. 

I was running the txbot with no luck.

But I pulled the git changes yesterday. `creditContract.balanceOf(delegatorAddr)` and `creditContract.getPooledBNB(delegatorAddr)`  now show the rewards being distributed and I can see the RewardDistributed events being fired off.
